version: '3.8'

services:
  radar-api:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: lassez-app:latest
    container_name: radar-api
    restart: always
    network_mode: host
    environment:
      - PORT=3001
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - /var/www/lassez-shared/prisma:/app/prisma
      - /var/www/lassez-shared/logs:/app/logs
      - /var/www/lassez-shared/radar_lassez/radar.db:/app/radar_lassez/radar.db
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/www/lassez-shared/media:/app/media

  radar-front:
    image: lassez-app:latest
    container_name: radar-front
    restart: always
    network_mode: host
    environment:
      - PORT=3000
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - /var/www/lassez-shared/prisma:/app/prisma
      - /var/www/lassez-shared/logs:/app/logs
      - /var/www/lassez-shared/radar_lassez/radar.db:/app/radar_lassez/radar.db
    depends_on:
      - radar-api

  radar-studio:
    image: lassez-app:latest
    container_name: radar-studio
    restart: always
    network_mode: host
    environment:
      - PORT=3002
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - /var/www/lassez-shared/prisma:/app/prisma
      - /var/www/lassez-shared/logs:/app/logs
      - /var/www/lassez-shared/radar_lassez/radar.db:/app/radar_lassez/radar.db
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/www/lassez-shared/media:/app/media
    depends_on:
      - radar-api

  radar-daemon:
    image: lassez-app:latest
    container_name: radar-daemon
    restart: always
    command: npx tsx ./radar_lassez/daemon.ts
    network_mode: host
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - /var/www/lassez-shared/prisma:/app/prisma
      - /var/www/lassez-shared/logs:/app/logs
      - /var/www/lassez-shared/radar_lassez/radar.db:/app/radar_lassez/radar.db
    depends_on:
      - radar-api


