/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    authors: AuthorAuthOperations;
  };
  blocks: {};
  collections: {
    categories: Category;
    tags: Tag;
    authors: Author;
    media: Media;
    posts: Post;
    lessons: Lesson;
    revelations: Revelation;
    signals: Signal;
    sources: Source;
    publications: Publication;
    'seen-urls': SeenUrl;
    'taxonomy-templates': TaxonomyTemplate;
    logs: Log;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    revelations: RevelationsSelect<false> | RevelationsSelect<true>;
    signals: SignalsSelect<false> | SignalsSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    'seen-urls': SeenUrlsSelect<false> | SeenUrlsSelect<true>;
    'taxonomy-templates': TaxonomyTemplatesSelect<false> | TaxonomyTemplatesSelect<true>;
    logs: LogsSelect<false> | LogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    about: About;
    legal: Legal;
    'radar-settings': RadarSetting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
    'radar-settings': RadarSettingsSelect<false> | RadarSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Author;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AuthorAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Taxonomie éditoriale principale du front.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Nom affiché de la catégorie.
   */
  name: string;
  /**
   * Slug auto-généré à partir du nom si besoin.
   */
  slug: string;
  /**
   * Texte éditorial optionnel affiché sur les pages catégorie.
   */
  description?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  sortOrder?: number | null;
  enabled?: boolean | null;
  /**
   * Afficher cette catégorie dans le menu de navigation principal.
   */
  showInHeader?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Étiquettes utilisées dans les dossiers et le flux éditorial.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Nom affiché de l’étiquette.
   */
  name: string;
  /**
   * Slug auto-généré à partir du nom si vide.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auteurs et comptes éditoriaux du média.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * Nom public ou signature éditoriale.
   */
  name: string;
  /**
   * Permissions de l’utilisateur. Seuls les admins peuvent modifier ce champ.
   */
  roles: ('admin' | 'editor' | 'author')[];
  /**
   * Slug auto-généré à partir du nom si vide.
   */
  slug: string;
  bio?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'authors';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Dossier éditorial avec preview, SEO et taxonomies.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Titre principal affiché sur le site et utilisé pour le slug si celui-ci est vide.
   */
  title: string;
  /**
   * Identifiant URL. Il est auto-rempli à partir du titre quand il est vide.
   */
  slug: string;
  /**
   * Accroche courte utilisée dans les cartes et le référencement social.
   */
  excerpt?: string | null;
  /**
   * Corps de l’article. C’est le contenu publié sur le front.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  content_html?: string | null;
  /**
   * Choisis au moins une catégorie pour déterminer le silo front et la route canonique.
   */
  categories: (number | Category)[];
  /**
   * Étiquettes optionnelles pour affiner le tri et les filtres.
   */
  tags?: (number | Tag)[] | null;
  /**
   * Auteur éditorial responsable du contenu.
   */
  author?: (number | null) | Author;
  /**
   * Image principale utilisée dans les listings et partages.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Date de publication. Si l’article passe en publié sans date, elle est renseignée automatiquement.
   */
  publishedAt?: string | null;
  /**
   * Champs additionnels flexibles (Advanced Custom Fields)
   */
  acf?: {
    /**
     * Points clés affichés sous forme de liste (un par ligne).
     */
    key_points?: string | null;
    /**
     * Données (JSON ou CSV) injectées dans le composant BarChart ou semblable.
     */
    chart_data?: string | null;
    /**
     * Lien source ou document de référence associé à l’article.
     */
    sourcePdfUrl?: string | null;
    /**
     * Niveau de confidentialité du contenu.
     */
    securityLevel?: ('PUBLIC' | 'CONFIDENTIEL') | null;
    /**
     * Métadonnée éditoriale spécifique au silo Comprendre.
     */
    chapitre_comprendre?: string | null;
    /**
     * Numéro de leçon spécifique au silo Comprendre.
     */
    lecon_comprendre?: number | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Silo Comprendre : Collection 100% didactique.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  title: string;
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  content_html?: string | null;
  /**
   * Le chapitre auquel appartient cette leçon.
   */
  chapitre: string;
  /**
   * L'ordre de la leçon dans le chapitre.
   */
  numero_lecon: number;
  niveau_difficulte?: ('debutant' | 'intermediaire' | 'avance') | null;
  /**
   * Fiche PDF récapitulative téléchargeable.
   */
  pdf_attachement?: (number | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Silo Révélations : Live feed orienté action rapide.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "revelations".
 */
export interface Revelation {
  id: number;
  titre: string;
  /**
   * Slug URL de la révélation, généré depuis le titre si vide.
   */
  slug: string;
  /**
   * Le contenu brut de la révélation.
   */
  contenu_rapide: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  contenu_rapide_html?: string | null;
  /**
   * Niveau de classification de la révélation.
   */
  niveau_alerte?: ('Public' | 'Confidentiel') | null;
  /**
   * Zone géographique principale de la révélation (utilisée pour le filtre front).
   */
  zone_geo?: ('france' | 'international') | null;
  /**
   * Tags thématiques pour le filtrage dans le flux Révélations.
   */
  tags?: (number | Tag)[] | null;
  /**
   * Auteur éditorial responsable de cette révélation.
   */
  author?: (number | null) | Author;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Sujets traités par le pipeline Radar (ingestion → publication).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signals".
 */
export interface Signal {
  id: number;
  /**
   * Titre du sujet (extrait du raw_data au premier accès).
   */
  source_title?: string | null;
  /**
   * Payload d’entrée du pipeline (cluster, articles agrégés, sources).
   */
  raw_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Payload de sortie éditorial (headline, body, image_keyword).
   */
  final_draft?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status:
    | 'INGESTED'
    | 'RESEARCHED'
    | 'DRAFTED'
    | 'VALIDATED'
    | 'PENDING'
    | 'QUEUED'
    | 'PUBLISHED'
    | 'REJECTED'
    | 'REJECTED_ERROR'
    | 'FAILED';
  /**
   * Catégorie éditoriale (INFO, DÉCRYPTAGE, ALERTE, …).
   */
  taxonomy?: string | null;
  /**
   * Tableau JSON des mots-clés.
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Zone géographique (FRANCE, INTERNATIONAL, …).
   */
  geo?: string | null;
  image_url?: string | null;
  /**
   * Moment où la file de publication doit traiter ce signal.
   */
  scheduled_at?: string | null;
  /**
   * Date exacte de publication finale.
   */
  published_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Flux et canaux ingérés par le daemon Radar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  url: string;
  type: 'RSS' | 'TELEGRAM' | 'GOOGLE_NEWS';
  source_name: string;
  /**
   * Orientation éditoriale perçue (Droite, Gauche, Service Public, …).
   */
  source_bias?: string | null;
  trust_score: number;
  /**
   * Autoriser l’usage des images de cette source dans les visuels.
   */
  allow_source_images?: boolean | null;
  active?: boolean | null;
  /**
   * État de santé du dernier scan (ex radar_source_health).
   */
  health_status?: ('OK' | 'ERROR' | 'TIMEOUT') | null;
  last_check_at?: string | null;
  error_message?: string | null;
  /**
   * Temps de réponse du dernier scan, en millisecondes.
   */
  response_time?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Missions de diffusion planifiées (réseaux sociaux + CMS).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  /**
   * Signal associé à cette mission de publication.
   */
  signal: number | Signal;
  /**
   * Plateforme de destination (DISCORD, X, BLUESKY, MASTODON, PAYLOAD).
   */
  platform: string;
  status: 'PENDING' | 'PUBLISHED' | 'FAILED';
  scheduled_at: string;
  published_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mémoire des URL déjà ingérées (dédoublonnage absolu).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seen-urls".
 */
export interface SeenUrl {
  id: number;
  url: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Formats éditoriaux (FLASH, CITATION, ALERTE…) pour les prompts IA.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomy-templates".
 */
export interface TaxonomyTemplate {
  id: number;
  /**
   * Identifiant technique (FLASH, CITATION, ALERTE…).
   */
  name: string;
  /**
   * Nom affiché (🚨 FLASH, ⚡️ CITATION…).
   */
  display_name?: string | null;
  description?: string | null;
  /**
   * Section de prompt spécifique à ce format.
   */
  format_instructions?: string | null;
  /**
   * Tableau JSON d’exemples de sortie.
   */
  examples_json?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Structure JSON attendue en sortie.
   */
  output_schema_json?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Couleur d’accentuation dans l’interface.
   */
  accent_color?: string | null;
  /**
   * Template d’usine : réinitialisable mais non supprimable.
   */
  is_factory?: boolean | null;
  active?: boolean | null;
  sort_order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Journal d’exécution du daemon Radar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logs".
 */
export interface Log {
  id: number;
  level: 'INFO' | 'WARN' | 'ERROR' | 'SUCCESS';
  message: string;
  /**
   * Nœud émetteur (Node 1, Node 2, Daemon, SYSTEM…).
   */
  node_id?: string | null;
  timestamp: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'revelations';
        value: number | Revelation;
      } | null)
    | ({
        relationTo: 'signals';
        value: number | Signal;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'seen-urls';
        value: number | SeenUrl;
      } | null)
    | ({
        relationTo: 'taxonomy-templates';
        value: number | TaxonomyTemplate;
      } | null)
    | ({
        relationTo: 'logs';
        value: number | Log;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'authors';
    value: number | Author;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'authors';
    value: number | Author;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  seoTitle?: T;
  seoDescription?: T;
  sortOrder?: T;
  enabled?: T;
  showInHeader?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  slug?: T;
  bio?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  content_html?: T;
  categories?: T;
  tags?: T;
  author?: T;
  featuredImage?: T;
  publishedAt?: T;
  acf?:
    | T
    | {
        key_points?: T;
        chart_data?: T;
        sourcePdfUrl?: T;
        securityLevel?: T;
        chapitre_comprendre?: T;
        lecon_comprendre?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  content_html?: T;
  chapitre?: T;
  numero_lecon?: T;
  niveau_difficulte?: T;
  pdf_attachement?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "revelations_select".
 */
export interface RevelationsSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  contenu_rapide?: T;
  contenu_rapide_html?: T;
  niveau_alerte?: T;
  zone_geo?: T;
  tags?: T;
  author?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signals_select".
 */
export interface SignalsSelect<T extends boolean = true> {
  source_title?: T;
  raw_data?: T;
  final_draft?: T;
  status?: T;
  taxonomy?: T;
  tags?: T;
  geo?: T;
  image_url?: T;
  scheduled_at?: T;
  published_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  url?: T;
  type?: T;
  source_name?: T;
  source_bias?: T;
  trust_score?: T;
  allow_source_images?: T;
  active?: T;
  health_status?: T;
  last_check_at?: T;
  error_message?: T;
  response_time?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  signal?: T;
  platform?: T;
  status?: T;
  scheduled_at?: T;
  published_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seen-urls_select".
 */
export interface SeenUrlsSelect<T extends boolean = true> {
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomy-templates_select".
 */
export interface TaxonomyTemplatesSelect<T extends boolean = true> {
  name?: T;
  display_name?: T;
  description?: T;
  format_instructions?: T;
  examples_json?: T;
  output_schema_json?: T;
  accent_color?: T;
  is_factory?: T;
  active?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logs_select".
 */
export interface LogsSelect<T extends boolean = true> {
  level?: T;
  message?: T;
  node_id?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Réglages globaux du site (Textes, Liens, Maintenance)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Modèle Gemini utilisé pour générer automatiquement les métadonnées SEO.
   */
  seoGeminiModel?:
    | (
        | 'gemini-3.1-pro-preview'
        | 'gemini-3.1-flash-lite-preview'
        | 'gemini-3-flash-preview'
        | 'gemini-2.5-flash'
        | 'gemini-2.5-flash-lite'
        | 'gemini-2.5-pro'
      )
    | null;
  displaySettings?: {
    flashInfoEnabled?: boolean | null;
    showHeader?: boolean | null;
    showFooter?: boolean | null;
  };
  /**
   * Texte par défaut si la liste ci-dessous est vide.
   */
  flashInfoText?: string | null;
  /**
   * Liste des messages défilants. Si actif, ils apparaîtront dans le bandeau.
   */
  tickerItems?:
    | {
        text: string;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Activer le mode maintenance au public.
   */
  maintenanceMode?: boolean | null;
  socialLinks?: {
    twitter?: string | null;
    telegram?: string | null;
    instagram?: string | null;
    bluesky?: string | null;
    mastodon?: string | null;
    tiktok?: string | null;
    linkedin?: string | null;
  };
  /**
   * Réglages Matomo pour les statistiques de visite.
   */
  matomoSettings?: {
    matomoId?: string | null;
    matomoUrl?: string | null;
  };
  /**
   * Configuration du manifest Web (PWA).
   */
  manifest: {
    siteName: string;
    shortName?: string | null;
    description?: string | null;
    themeColor?: string | null;
    backgroundColor?: string | null;
  };
  /**
   * Configurez les liens du menu principal dans le header.
   */
  navigation?:
    | {
        label: string;
        enabled?: boolean | null;
        badge?: string | null;
        linkType?: ('custom' | 'category') | null;
        customUrl?: string | null;
        category?: (number | null) | Category;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Éditez le Manifeste et la présentation de l’équipe.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  title: string;
  version?: string | null;
  introText: string;
  manifestoSections?:
    | {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        variant?: ('red' | 'black') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Citation mise en avant (bloc jaune).
   */
  quote?: string | null;
  signature?: {
    line1?: string | null;
    line2?: string | null;
  };
  team?:
    | {
        name: string;
        role: string;
        avatar?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Éditez les informations légales et la politique de confidentialité.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: number;
  title: string;
  lastUpdated?: string | null;
  sections?:
    | {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        highlightBox?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configuration globale du pipeline Radar (sources, IA, diffusion, planification).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radar-settings".
 */
export interface RadarSetting {
  id: number;
  enableAutoPublish?: boolean | null;
  enablePayloadCMS?: boolean | null;
  includeSourceUrl?: boolean | null;
  enableDiscord?: boolean | null;
  discordPublishMode?: ('DIRECT' | 'SCHEDULED') | null;
  discordEmbedColor?: string | null;
  discordFooterText?: string | null;
  /**
   * Secret — laisser vide pour conserver la valeur actuelle.
   */
  discordWebhookUrl?: string | null;
  enableX?: boolean | null;
  xPublishMode?: ('DIRECT' | 'SCHEDULED') | null;
  xMaxLength?: number | null;
  /**
   * Secret — laisser vide pour conserver la valeur actuelle.
   */
  xApiKey?: string | null;
  /**
   * Secret — laisser vide pour conserver la valeur actuelle.
   */
  xApiSecret?: string | null;
  /**
   * Secret — laisser vide pour conserver la valeur actuelle.
   */
  xAccessToken?: string | null;
  /**
   * Secret — laisser vide pour conserver la valeur actuelle.
   */
  xAccessSecret?: string | null;
  enableBluesky?: boolean | null;
  blueskyPublishMode?: ('DIRECT' | 'SCHEDULED') | null;
  blueskyMaxLength?: number | null;
  /**
   * Secret — laisser vide pour conserver la valeur actuelle.
   */
  blueskyIdentifier?: string | null;
  /**
   * Secret — laisser vide pour conserver la valeur actuelle.
   */
  blueskyAppPassword?: string | null;
  enableMastodon?: boolean | null;
  mastodonPublishMode?: ('DIRECT' | 'SCHEDULED') | null;
  mastodonMaxLength?: number | null;
  /**
   * Secret — laisser vide pour conserver la valeur actuelle.
   */
  mastodonInstanceUrl?: string | null;
  /**
   * Secret — laisser vide pour conserver la valeur actuelle.
   */
  mastodonAccessToken?: string | null;
  payloadPublishMode?: ('DIRECT' | 'SCHEDULED') | null;
  /**
   * Secret — laisser vide pour conserver la valeur actuelle.
   */
  payloadServerUrl?: string | null;
  /**
   * Secret — laisser vide pour conserver la valeur actuelle.
   */
  payloadBotEmail?: string | null;
  /**
   * Secret — laisser vide pour conserver la valeur actuelle.
   */
  payloadBotPassword?: string | null;
  schedulingMode?: ('pulse' | 'calendar' | 'hybrid') | null;
  scrapingInterval?: number | null;
  minPublishDelay?: number | null;
  maxPublishDelay?: number | null;
  daemonSchedule?: string | null;
  /**
   * Secret — laisser vide pour conserver la valeur actuelle.
   */
  geminiApiKey?: string | null;
  maxConcurrentTasks?: number | null;
  similarityThreshold?: number | null;
  dedupLookbackHours?: number | null;
  aiModelFlash?: string | null;
  aiModelPro?: string | null;
  customPromptModifier?: string | null;
  allowSourceImages?: boolean | null;
  baseIdentityPrompt?: string | null;
  researchMissionPrompt?: string | null;
  vocabularyRulesPrompt?: string | null;
  imageRulesPrompt?: string | null;
  researcherSystemPrompt?: string | null;
  researcherRejectCriteria?: string | null;
  rss_feeds?: string | null;
  telegram_channels?: string | null;
  google_news_queries?: string | null;
  keywords?: string | null;
  bannedKeywords?: string | null;
  pipelineGraphJson?: string | null;
  social_targets_by_type_json?: string | null;
  availableModelsJson?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  seoGeminiModel?: T;
  displaySettings?:
    | T
    | {
        flashInfoEnabled?: T;
        showHeader?: T;
        showFooter?: T;
      };
  flashInfoText?: T;
  tickerItems?:
    | T
    | {
        text?: T;
        active?: T;
        id?: T;
      };
  maintenanceMode?: T;
  socialLinks?:
    | T
    | {
        twitter?: T;
        telegram?: T;
        instagram?: T;
        bluesky?: T;
        mastodon?: T;
        tiktok?: T;
        linkedin?: T;
      };
  matomoSettings?:
    | T
    | {
        matomoId?: T;
        matomoUrl?: T;
      };
  manifest?:
    | T
    | {
        siteName?: T;
        shortName?: T;
        description?: T;
        themeColor?: T;
        backgroundColor?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        enabled?: T;
        badge?: T;
        linkType?: T;
        customUrl?: T;
        category?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  title?: T;
  version?: T;
  introText?: T;
  manifestoSections?:
    | T
    | {
        title?: T;
        content?: T;
        variant?: T;
        id?: T;
      };
  quote?: T;
  signature?:
    | T
    | {
        line1?: T;
        line2?: T;
      };
  team?:
    | T
    | {
        name?: T;
        role?: T;
        avatar?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  title?: T;
  lastUpdated?: T;
  sections?:
    | T
    | {
        title?: T;
        content?: T;
        highlightBox?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radar-settings_select".
 */
export interface RadarSettingsSelect<T extends boolean = true> {
  enableAutoPublish?: T;
  enablePayloadCMS?: T;
  includeSourceUrl?: T;
  enableDiscord?: T;
  discordPublishMode?: T;
  discordEmbedColor?: T;
  discordFooterText?: T;
  discordWebhookUrl?: T;
  enableX?: T;
  xPublishMode?: T;
  xMaxLength?: T;
  xApiKey?: T;
  xApiSecret?: T;
  xAccessToken?: T;
  xAccessSecret?: T;
  enableBluesky?: T;
  blueskyPublishMode?: T;
  blueskyMaxLength?: T;
  blueskyIdentifier?: T;
  blueskyAppPassword?: T;
  enableMastodon?: T;
  mastodonPublishMode?: T;
  mastodonMaxLength?: T;
  mastodonInstanceUrl?: T;
  mastodonAccessToken?: T;
  payloadPublishMode?: T;
  payloadServerUrl?: T;
  payloadBotEmail?: T;
  payloadBotPassword?: T;
  schedulingMode?: T;
  scrapingInterval?: T;
  minPublishDelay?: T;
  maxPublishDelay?: T;
  daemonSchedule?: T;
  geminiApiKey?: T;
  maxConcurrentTasks?: T;
  similarityThreshold?: T;
  dedupLookbackHours?: T;
  aiModelFlash?: T;
  aiModelPro?: T;
  customPromptModifier?: T;
  allowSourceImages?: T;
  baseIdentityPrompt?: T;
  researchMissionPrompt?: T;
  vocabularyRulesPrompt?: T;
  imageRulesPrompt?: T;
  researcherSystemPrompt?: T;
  researcherRejectCriteria?: T;
  rss_feeds?: T;
  telegram_channels?: T;
  google_news_queries?: T;
  keywords?: T;
  bannedKeywords?: T;
  pipelineGraphJson?: T;
  social_targets_by_type_json?: T;
  availableModelsJson?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}